# Generated by Django 4.2 on 2023-04-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_location_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='long',
            new_name='lng',
        ),
    ]
