# Generated by Django 4.2 on 2023-04-04 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_rename_long_location_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default=None, upload_to='ads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.user'),
            preserve_default=False,
        ),
    ]
