# Generated by Django 4.2 on 2023-04-04 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_category_ad_image_ad_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='user',
        ),
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.user'),
        ),
    ]
