# Generated by Django 4.2 on 2023-04-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_location_alter_user_options_user_age_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(default=None, to='authentication.location'),
        ),
    ]
